# Chapter 4 Numpy

In [1]:
import numpy as np

## Generate ny array

In [2]:
data = np.random.randn(2,3)
data

array([[-1.22119125,  0.23478976,  0.54532051],
       [-0.1566177 ,  1.55659422,  0.21744665]])

In [3]:
data * 10

array([[-12.21191253,   2.34789765,   5.45320507],
       [ -1.56617695,  15.56594221,   2.17446648]])

In [4]:
data + data 

array([[-2.44238251,  0.46957953,  1.09064101],
       [-0.31323539,  3.11318844,  0.4348933 ]])

In [5]:
data1 = [6,7.5,8., 0., 1.]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [6]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.size

8

In [11]:
arr2.shape

(2, 4)

In [14]:
arr2.dtype

dtype('int64')

In [16]:
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [17]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
print(arr2.dtype)
float_arr2 = arr2.astype(np.float16)
print(float_arr2.dtype)

int64
float16


## Math Calculation

In [27]:
arr2 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
arr2 * arr2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [31]:
arr2_2 = arr2 * arr2
arr2_2 > arr2

array([[False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [32]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [33]:
arr1[2]

8.0

## Slicing Array

In [36]:
#slice of data is a view of original array, change will reflect in original array as well
arr_org = np.array([1,3,6,9,2,4])
arr_org

array([1, 3, 6, 9, 2, 4])

In [39]:
arr_slice = arr_org[2:4]
arr_slice

array([6, 9])

In [40]:
arr_slice[:] = 1000
arr_org

array([   1,    3, 1000, 1000,    2,    4])

In [41]:
#if one need a copy of original array, need .copy command
arr_slice2 = arr_org[1:3].copy()
arr_slice2

array([   3, 1000])

In [42]:
arr_slice2[:] = -100
arr_org

array([   1,    3, 1000, 1000,    2,    4])

## Multiple Dimension arrary reference

In [43]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
arr2[1]

array([5, 6, 7, 8])

In [46]:
arr2[1][2]

7

In [47]:
arr2[1,2]

7

In [49]:
arr2[:, 2:]

array([[3, 4],
       [7, 8]])

## Passing boolen as index into array

In [54]:
selected = np.array([1,0,0,1,0])
selected == 1

array([ True, False, False,  True, False], dtype=bool)

In [55]:
rand = np.random.randn(5,5)

In [56]:
rand

array([[-0.04497178,  1.71561351, -0.12703563, -0.81655568, -0.21640375],
       [-0.68439521,  1.13743107,  0.2695173 ,  0.51053255,  0.05747783],
       [ 0.00453966,  0.14620982, -1.54359317,  0.76154033, -0.53344998],
       [ 0.62672362, -1.02982701, -0.87222374,  0.5317196 ,  1.44125261],
       [ 0.92697044,  0.86856174, -0.02652225,  0.99016902,  0.78993514]])

In [58]:
rand[selected==1] #only the first and forth row will be selected

array([[-0.04497178,  1.71561351, -0.12703563, -0.81655568, -0.21640375],
       [ 0.62672362, -1.02982701, -0.87222374,  0.5317196 ,  1.44125261]])

In [59]:
rand[selected==1, 3:] #selected==1 can be passed like parameter

array([[-0.81655568, -0.21640375],
       [ 0.5317196 ,  1.44125261]])

In [60]:
rand[rand<0]=100

In [61]:
rand

array([[  1.00000000e+02,   1.71561351e+00,   1.00000000e+02,
          1.00000000e+02,   1.00000000e+02],
       [  1.00000000e+02,   1.13743107e+00,   2.69517303e-01,
          5.10532546e-01,   5.74778296e-02],
       [  4.53965578e-03,   1.46209821e-01,   1.00000000e+02,
          7.61540328e-01,   1.00000000e+02],
       [  6.26723622e-01,   1.00000000e+02,   1.00000000e+02,
          5.31719595e-01,   1.44125261e+00],
       [  9.26970439e-01,   8.68561744e-01,   1.00000000e+02,
          9.90169019e-01,   7.89935138e-01]])

## Reorder the rows in 2 dimension array

In [62]:
arr_o = np.empty((8,4))
for i in range(8):
    arr_o[i] = i

arr_o

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [64]:
arr_o[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [66]:
arr_o2 = np.arange(32).reshape((8,4))
arr_o2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [67]:
arr_o2[[1,5,7,2],[0,1,3,2]]

array([ 4, 21, 31, 10])

## Transforming

In [68]:
arr_t = np.arange(15).reshape(3,5)
arr_t

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
arr_t.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])